import { GoogleGenAI } from "@google/genai";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found in environment variables.");
  }
  return new GoogleGenAI({ apiKey });
};

/**
 * Uses Gemini 2.5 Flash Image to edit/process an image based on a text prompt.
 */
export const editDocumentImage = async (base64Image: string, prompt: string): Promise<string> => {
  try {
    const client = getClient();
    const model = 'gemini-2.5-flash-image';

    const response = await client.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png',
              data: base64Image.replace(/^data:image\/\w+;base64,/, ''),
            },
          },
          {
            text: `Edit this document image: ${prompt}. Return only the image.`,
          },
        ],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData && part.inlineData.data) {
        return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by Gemini.");
  } catch (error) {
    console.error("Gemini Image Edit Error:", error);
    throw error;
  }
};

/**
 * Uses Gemini to extract the Barcode or WO Number from an image
 */
export const extractDataFromImage = async (base64Image: string): Promise<string | null> => {
  try {
    const client = getClient();
    // Using a fast model for text extraction
    const model = 'gemini-2.5-flash-latest';

    const response = await client.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg', 
              data: base64Image.replace(/^data:image\/\w+;base64,/, ''),
            },
          },
          {
            text: `Extract the main numeric identifier from this image (Barcode or Text). 
            It is a Maintenance Work Order. 
            Rules:
            1. Look for a 9-digit number starting with 100, 101, or 200.
            2. Ignore dates or small labels.
            3. Return ONLY the digits. No text like "WO:" or "Barcode:".
            4. If multiple numbers exist, prefer the one starting with 100, 101, or 200.
            5. If absolutely no valid number is found, return "null".`,
          },
        ],
      },
    });

    const text = response.text?.trim();
    if (!text || text.toLowerCase().includes('null')) return null;
    
    // Clean up result, keep only numbers
    const numbers = text.replace(/\D/g, '');
    
    // Validar se parece um documento real
    if (numbers.length >= 5) {
        return numbers;
    }
    return null;

  } catch (error) {
    console.error("Gemini Extraction Error:", error);
    return null;
  }
};