import { GoogleGenAI } from "@google/genai";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found in environment variables.");
  }
  return new GoogleGenAI({ apiKey });
};

/**
 * Uses Gemini 2.5 Flash Image to edit/process an image based on a text prompt.
 * Examples: "Remove background", "Enhance text readability", "Convert to grayscale".
 */
export const editDocumentImage = async (base64Image: string, prompt: string): Promise<string> => {
  try {
    const client = getClient();
    
    // Using the requested model for image editing/generation tasks
    // 'gemini-2.5-flash-image' is the mapped name for 'nano banana' or 'gemini flash image'
    const model = 'gemini-2.5-flash-image';

    // To edit images, we pass the original image + a text prompt instructing the edit.
    // The model generates a NEW image based on these inputs.
    const response = await client.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png', // Assuming PNG for this demo, usually should detect
              data: base64Image.replace(/^data:image\/\w+;base64,/, ''),
            },
          },
          {
            text: `Edit this document image: ${prompt}. Return only the image.`,
          },
        ],
      },
    });

    // Check for image in response (inlineData)
    // The response structure for images usually contains the image in parts
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData && part.inlineData.data) {
        return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image generated by Gemini.");

  } catch (error) {
    console.error("Gemini Image Edit Error:", error);
    throw error;
  }
};